Add Proposal C
opencontainers/wg-reference-types pull request #22
Opened 2022-03-08 21:19 UTC by nishakm

Signed-off-by: nisha <nisha@ctlfsh.tech>

2022-03-08 21:45 UTC, jdolitsky requested changes
Awesome! Can you add the short description to the README?

2022-03-08 21:49 UTC, jdolitsky commented on docs/proposals/PROPOSAL_C.md
> +No modifications to existing JSON schemas or APIs are required. A new object is introduced instead.
Perhaps just drop this line.. There are indeed new endpoints introduced in the registry section, but reader can go there to learn more

2022-03-08 21:52 UTC, jdolitsky commented on docs/proposals/PROPOSAL_C.md
> +No modifications to existing JSON schemas or APIs are required. A new object is introduced instead.
or rather, place it under "JSON Schema"

2022-03-09 15:10 UTC, sudo-bmitch approved these changes
I've left some question inline that I'll have when we review. Those don't need to be answered before merging this.

2022-03-09 15:10 UTC, sudo-bmitch commented on docs/proposals/PROPOSAL_C.md
> +  }
Is it possible for a reference to point to a digest that exists in the above object list, or one of the children of those objects? And if so, how should registries handle this with GC policies (there's could be a reference loop)?

2022-03-09 15:10 UTC, sudo-bmitch commented on docs/proposals/PROPOSAL_C.md
> +#### Objects contained in a node manifest
Do we need to use the objects API, or could the existing blob and manifest APIs be used? If the latter, how would clients know which of the two sets of APIs to use? I'm thinking of this from a client that wants to copy images between registries, or some other higher level activity,  but that doesn't know the new media types.

2022-03-09 15:17 UTC, imjasonh commented on docs/proposals/PROPOSAL_C.md
> +  "schemaVersion": 3,
How do v3 objects relate to v2 objects, especially v2 objects which already exist in the registry?

Are all existing OCI images in a registry also available as v3 Nodes that I can attach to, or do I have to push them as Nodes separately to be able to attach them? This is especially relevant for blobs -- we definitely don't want clients to have to push blobs twice, or for registries to have to store them twice.

2022-03-09 16:30 UTC, jdolitsky approved these changes
The formatting looks good. The questions raised above can probably be addressed when we review this.

Nisha - your call to merge whenever youre ready to do so

2022-03-09 16:54 UTC, imjasonh approved these changes
+1 to merging, we can discuss points either here in the PR, or in a future WG meeting.

Thanks for adding this Nisha!

2022-03-09 20:35 UTC, merged