Make filtering user stories more clear
opencontainers/wg-reference-types pull request #25
Opened 2022-03-09 21:36 UTC by nishakm

During the group's first attempt at evaluating a proposal, there
were different interpretations of the filtering user stories.
Hopefully these adjustments would make them more clear.

Signed-off-by: nisha <nisha@ctlfsh.tech>

2022-03-10 00:58 UTC, sudo-bmitch requested changes
Other than reverting F3, these LGTM.

2022-03-10 00:58 UTC, sudo-bmitch commented on docs/REQUIREMENTS.md
> +1. As a user, I want to query a registry for all stored artifacts of a particular type.
I like the "that reference another artifact by its tag and digest" qualifier on this, I don't need every sbom in the repository, just the sbom associated with my particular image, but without fetching every attestation and signature.

2022-03-10 16:37 UTC, jdolitsky approved these changes

2022-03-10 17:18 UTC, sudo-bmitch approved these changes

2022-03-14 17:57 UTC, nishakm commented
@jdolitsky OK to merge this?

2022-03-14 17:59 UTC, merged