Add 2022-03-15 minutes
opencontainers/wg-reference-types pull request #28
Opened 2022-03-15 19:05 UTC by lachie83

Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>

2022-03-15 23:43 UTC, sudo-bmitch requested changes
Just a couple typos. Thank you for doing the note taking this week Lachlan!

2022-03-15 23:43 UTC, sudo-bmitch commented on minutes/2022-03-15.md
> +   -  When we're looking at objects field, are they manifest or objects or both and how are they accessed and interact? (Brandan)
```suggestion
   -  When we're looking at objects field, are they manifest or blobs or both and how are they accessed and interact? (Brandon)
```

2022-03-15 23:43 UTC, sudo-bmitch commented on minutes/2022-03-15.md
> +   -  If I copy this a registry th at supports v3 to a registry that supports v2? (Brandon)
```suggestion
   -  If I copy this from a registry that supports v3 to a registry that supports v2? (Brandon)
```

2022-03-21 23:35 UTC, lachie83 commented on minutes/2022-03-15.md
> +   -  If I copy this a registry th at supports v3 to a registry that supports v2? (Brandon)
Thanks Brandon - Will fix

2022-03-22 17:57 UTC, sudo-bmitch approved these changes

2022-03-22 19:37 UTC, SteveLasker approved these changes

2022-03-22 20:15 UTC, imjasonh approved these changes

2022-03-22 20:15 UTC, merged